services:
  mongo:
    image: mongo:6
    container_name: eventpulse_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: eventpulse_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: eventpulse_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_HOST=redis://redis:6379
      - DATABASE_NAME=eventpulse_db

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: eventpulse_worker
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_HOST=redis://redis:6379

volumes:
  mongo_data:
  redis_data: